[package]
name = "bench-json"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
json_escape = { package = "json-escape", version = "0.3" }
v_jsonescape = "0.9"
simd-json = "0.17"
sonic-rs = "0.5"

[[bench]]
name = "escape"
harness = false
